"""The synthetic 'no provider reachable' reply must be identifiable.

It is chat-shaped prose generated by ClimateIQ itself, not a model decision.
Without a machine-readable marker, ClimateAdvisor tried to parse it as JSON and
reported "No JSON found in LLM response" — blaming the model for what was
actually a connectivity outage.
"""

from backend.integrations.llm.provider import ClimateIQLLMProvider, ProviderSettings

MESSAGES = [
    {"role": "system", "content": "You are the ClimateIQ smart thermostat advisor."},
    {"role": "user", "content": "─── CURRENT STATE ───\nHVAC mode: cool\n"},
]


def _provider() -> ClimateIQLLMProvider:
    return ClimateIQLLMProvider(
        primary=ProviderSettings(provider="ollama", base_url="http://127.0.0.1:1")
    )


def test_fallback_is_flagged_as_provider_unavailable():
    resp = _provider()._rule_based_fallback(MESSAGES, request_id="req-1")
    assert resp["climateiq_provider_unavailable"] is True


def test_fallback_still_returns_readable_prose_for_the_chat_ui():
    """Human-facing graceful degradation must survive — only the flag is new."""
    resp = _provider()._rule_based_fallback(MESSAGES, request_id="req-2")
    content = resp["choices"][0]["message"]["content"]
    assert "cannot reach any configured LLM provider" in content
    assert resp["model"] == "rule-based"


def test_marker_is_absent_from_a_normal_response_shape():
    """A real provider reply has no marker, so the advisor parses it as before."""
    real = {
        "id": "x", "object": "chat.completion", "model": "qwen2.5:7b",
        "choices": [{"index": 0, "finish_reason": "stop",
                     "message": {"role": "assistant", "content": '{"action":"hold"}'}}],
    }
    assert not real.get("climateiq_provider_unavailable")
